#!/bin/sh
#. "$(dirname "$0")/_/husky.sh"
echo 'Start checking JavaScript files:'
npx eslint **/*.js --format table 
echo "Now let's fix problems"
npx eslint --fix
echo '**** Allright! Going to commit ****'
#undefined
